services:
  proxy:
    container_name: swarmly-proxy
    build:
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - ./:/app
      - cargo-cache:/usr/local/cargo
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    container_name: swarmly-api
    image: magwoo/helloworld:latest
    labels:
      - proxy.domain=app.ru

volumes:
  cargo-cache:

