services:
  proxy:
    image: magwoo/swarmly:latest
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    image: magwoo/helloworld:latest
    labels:
      - proxy.domain=app.ru
    deploy:
      replicas: 2
