services:
  redis:
    image: redis:7-alpine

  proxy:
    build:
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - 80:80
      - 443:443
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
      - cargo-cache:/usr/local/cargo
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis

  api:
    image: caddy:2-alpine
    labels:
      - proxy.domain=app.ru
    deploy:
      replicas: 3

volumes:
  cargo-cache:
