services:
  proxy:
    image: magwoo/swarmly:latest
    build:
      dockerfile: docker/Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
