FROM rust:1.91-alpine3.23 AS runtime
WORKDIR /app

RUN apk add --no-cache build-base cmake watchexec perl
RUN echo "while true; do cargo run; sleep 1; done" > /bin/rerun.sh
RUN chmod +x /bin/rerun.sh

ENTRYPOINT ["watchexec", "-r", "-e", "rs,toml", "rerun.sh"]
