name: Build and publish docker container

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-amd64:
    runs-on: ubuntu-22.04
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: Build and push `swarmly` docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file docker/Dockerfile.prod \
            --cache-from type=registry,ref=ghcr.io/magwoo/swarmly-cache:amd64 \
            --cache-to type=registry,ref=ghcr.io/magwoo/swarmly-cache:amd64,mode=max \
            --tag ghcr.io/magwoo/swarmly:amd64 \
            --push \
            .

  build-arm64:
    runs-on: ubuntu-22.04-arm
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: Build and push `swarmly` docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --file docker/Dockerfile.prod \
            --cache-from type=registry,ref=ghcr.io/magwoo/swarmly-cache:arm64 \
            --cache-to type=registry,ref=ghcr.io/magwoo/swarmly-cache:arm64,mode=max \
            --tag ghcr.io/magwoo/swarmly:arm64 \
            --push \
            .

  manifest-prepare:
    needs:
      - build-amd64
      - build-arm64
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/magwoo/swarmly:latest \
            -t ghcr.io/magwoo/swarmly:${GITHUB_SHA} \
            ghcr.io/magwoo/swarmly:amd64 \
            ghcr.io/magwoo/swarmly:arm64

