name: Build and publish docker container

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use

      - name: Build and push `swarmly` docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file docker/Dockerfile.prod \
            --cache-from type=registry,ref=ghcr.io/magwoo/swarmly:cache \
            --cache-to type=registry,ref=ghcr.io/magwoo/swarmly:cache,mode=max \
            --tag ghcr.io/magwoo/swarmly:latest \
            --tag ghcr.io/magwoo/swarmly:${GITHUB_SHA} \
            --push \
            .
